stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile.alpine
      buildContext: .
      tag: apcenter/hc
      pushRemote: true
      registry: index.docker.io
  when:
    branch:
      include:
      - master
timeout: 60
